In [1]:
# !pip install openpyxl
import pandas as pd 
import datetime

In [2]:
historical_cleaned = pd.read_parquet("./data_cleaned/yield_curve_historical_rates_MASTER.parquet")

historical_cleaned = (historical_cleaned
                      [historical_cleaned["Date"] <= "2024-03-28"]
                      .copy()
                      .reset_index()
                      .drop(columns=["index"])) 

historical_cleaned.head()

,Date,1 Mo,2 Mo,3 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr,2 Yr - 10 Yr,2 Yr - 30 Yr,10 Yr - 30 Yr
0,2024-03-28,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
1,2024-03-27,5.50,5.47,5.45,5.36,4.99,4.54,4.36,4.18,4.18,4.20,4.45,4.36,0.34,0.18,-0.16
2,2024-03-26,5.50,5.47,5.46,5.36,5.00,4.56,4.38,4.22,4.23,4.24,4.49,4.40,0.32,0.16,-0.16
3,2024-03-25,5.51,5.48,5.46,5.36,5.00,4.54,4.39,4.23,4.25,4.25,4.51,4.42,0.29,0.12,-0.17
4,2024-03-24,5.51,5.47,5.46,5.34,4.98,4.59,4.36,4.20,4.22,4.22,4.47,4.39,0.37,0.20,-0.17

In [7]:
df = pd.read_excel("./data_raw/daily-treasury-rates.xlsx")
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%Y-%m-%d")
df = df[df["Date"] > "2024-03-28"].copy()
df["2 Yr - 10 Yr"] = df["2 Yr"] - df["10 Yr"] 
df["2 Yr - 30 Yr"] = df["2 Yr"] - df["30 Yr"] 
df["10 Yr - 30 Yr"] = df["10 Yr"] - df["30 Yr"] 
df.drop(columns = ["4 Mo"], inplace = True)
df

,Date,1 Mo,2 Mo,3 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr,2 Yr - 10 Yr,2 Yr - 30 Yr,10 Yr - 30 Yr
0,2024-04-16,5.49,5.51,5.45,5.39,5.18,4.97,4.83,4.69,4.69,4.67,4.88,4.77,0.30,0.20,-0.10
1,2024-04-15,5.49,5.51,5.45,5.38,5.16,4.93,4.78,4.65,4.65,4.63,4.85,4.74,0.30,0.19,-0.11
2,2024-04-14,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
3,2024-04-13,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
4,2024-04-12,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
5,2024-04-11,5.48,5.51,5.45,5.38,5.17,4.93,4.77,4.61,4.60,4.56,4.77,4.65,0.37,0.28,-0.09
6,2024-04-10,5.49,5.50,5.45,5.40,5.19,4.97,4.77,4.61,4.59,4.55,4.76,4.64,0.42,0.33,-0.09
7,2024-04-09,5.48,5.49,5.43,5.34,5.03,4.74,4.52,4.37,4.38,4.36,4.60,4.50,0.38,0.24,-0.14
8,2024-04-08,5.48,5.49,5.43,5.35,5.07,4.78,4.60,4.43,4.43,4.42,4.65,4.55,0.36,0.23,-0.13
9,2024-04-07,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
10,2024-04-06,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
11,2024-04-05,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
12,2024-04-04,5.47,5.49,5.41,5.32,5.00,4.65,4.46,4.30,4.31,4.31,4.57,4.47,0.34,0.18,-0.16
13,2024-04-03,5.47,5.44,5.42,5.33,5.03,4.68,4.48,4.34,4.36,4.36,4.61,4.51,0.32,0.17,-0.15
14,2024-04-02,5.49,5.45,5.42,5.34,5.05,4.70,4.51,4.35,4.37,4.36,4.61,4.51,0.34,0.19,-0.15
15,2024-04-01,5.49,5.47,5.44,5.36,5.06,4.72,4.51,4.34,4.33,4.33,4.58,4.47,0.39,0.25,-0.14
16,2024-03-31,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
17,2024-03-30,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
18,2024-03-29,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14

In [9]:
pd.concat([df, historical_cleaned]).to_parquet("./data_cleaned/yield_curve_historical_rates_MASTER.parquet", index=False)

In [11]:
historical_cleaned = pd.read_parquet("./data_cleaned/yield_curve_historical_rates_MASTER.parquet")
historical_cleaned.head(50)

,Date,1 Mo,2 Mo,3 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr,2 Yr - 10 Yr,2 Yr - 30 Yr,10 Yr - 30 Yr
0,2024-04-16,5.49,5.51,5.45,5.39,5.18,4.97,4.83,4.69,4.69,4.67,4.88,4.77,0.30,0.20,-0.10
1,2024-04-15,5.49,5.51,5.45,5.38,5.16,4.93,4.78,4.65,4.65,4.63,4.85,4.74,0.30,0.19,-0.11
2,2024-04-14,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
3,2024-04-13,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
4,2024-04-12,5.48,5.50,5.45,5.36,5.13,4.88,4.70,4.54,4.53,4.50,4.73,4.61,0.38,0.27,-0.11
5,2024-04-11,5.48,5.51,5.45,5.38,5.17,4.93,4.77,4.61,4.60,4.56,4.77,4.65,0.37,0.28,-0.09
6,2024-04-10,5.49,5.50,5.45,5.40,5.19,4.97,4.77,4.61,4.59,4.55,4.76,4.64,0.42,0.33,-0.09
7,2024-04-09,5.48,5.49,5.43,5.34,5.03,4.74,4.52,4.37,4.38,4.36,4.60,4.50,0.38,0.24,-0.14
8,2024-04-08,5.48,5.49,5.43,5.35,5.07,4.78,4.60,4.43,4.43,4.42,4.65,4.55,0.36,0.23,-0.13
9,2024-04-07,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
10,2024-04-06,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
11,2024-04-05,5.47,5.50,5.43,5.34,5.05,4.73,4.54,4.38,4.39,4.39,4.65,4.54,0.34,0.19,-0.15
12,2024-04-04,5.47,5.49,5.41,5.32,5.00,4.65,4.46,4.30,4.31,4.31,4.57,4.47,0.34,0.18,-0.16
13,2024-04-03,5.47,5.44,5.42,5.33,5.03,4.68,4.48,4.34,4.36,4.36,4.61,4.51,0.32,0.17,-0.15
14,2024-04-02,5.49,5.45,5.42,5.34,5.05,4.70,4.51,4.35,4.37,4.36,4.61,4.51,0.34,0.19,-0.15
15,2024-04-01,5.49,5.47,5.44,5.36,5.06,4.72,4.51,4.34,4.33,4.33,4.58,4.47,0.39,0.25,-0.14
16,2024-03-31,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
17,2024-03-30,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
18,2024-03-29,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
19,2024-03-28,5.49,5.48,5.46,5.38,5.03,4.59,4.40,4.21,4.20,4.20,4.45,4.34,0.39,0.25,-0.14
20,2024-03-27,5.50,5.47,5.45,5.36,4.99,4.54,4.36,4.18,4.18,4.20,4.45,4.36,0.34,0.18,-0.16
21,2024-03-26,5.50,5.47,5.46,5.36,5.00,4.56,4.38,4.22,4.23,4.24,4.49,4.40,0.32,0.16,-0.16
22,2024-03-25,5.51,5.48,5.46,5.36,5.00,4.54,4.39,4.23,4.25,4.25,4.51,4.42,0.29,0.12,-0.17
23,2024-03-24,5.51,5.47,5.46,5.34,4.98,4.59,4.36,4.20,4.22,4.22,4.47,4.39,0.37,0.20,-0.17
24,2024-03-23,5.51,5.47,5.46,5.34,4.98,4.59,4.36,4.20,4.22,4.22,4.47,4.39,0.37,0.20,-0.17
25,2024-03-22,5.51,5.47,5.46,5.34,4.98,4.59,4.36,4.20,4.22,4.22,4.47,4.39,0.37,0.20,-0.17
26,2024-03-21,5.51,5.48,5.48,5.36,5.01,4.62,4.42,4.26,4.28,4.27,4.53,4.44,0.35,0.18,-0.17
27,2024-03-20,5.50,5.47,5.47,5.36,5.01,4.59,4.41,4.25,4.28,4.27,4.53,4.45,0.32,0.14,-0.18
28,2024-03-19,5.52,5.48,5.48,5.39,5.06,4.68,4.47,4.31,4.31,4.30,4.54,4.44,0.38,0.24,-0.14
29,2024-03-18,5.52,5.48,5.48,5.39,5.06,4.73,4.52,4.36,4.35,4.34,4.57,4.46,0.39,0.27,-0.12
30,2024-03-17,5.52,5.48,5.48,5.38,5.05,4.72,4.51,4.33,4.33,4.31,4.55,4.43,0.41,0.29,-0.12
31,2024-03-16,5.52,5.48,5.48,5.38,5.05,4.72,4.51,4.33,4.33,4.31,4.55,4.43,0.41,0.29,-0.12
32,2024-03-15,5.52,5.48,5.48,5.38,5.05,4.72,4.51,4.33,4.33,4.31,4.55,4.43,0.41,0.29,-0.12
33,2024-03-14,5.52,5.48,5.48,5.38,5.04,4.68,4.46,4.29,4.30,4.29,4.54,4.44,0.39,0.24,-0.15
34,2024-03-13,5.52,5.47,5.48,5.37,5.01,4.61,4.37,4.19,4.20,4.19,4.45,4.35,0.42,0.26,-0.16
35,2024-03-12,5.52,5.48,5.48,5.37,5.00,4.58,4.33,4.15,4.16,4.16,4.42,4.31,0.42,0.27,-0.15
36,2024-03-11,5.50,5.47,5.48,5.35,4.95,4.51,4.26,4.08,4.09,4.10,4.36,4.26,0.41,0.25,-0.16
37,2024-03-10,5.51,5.48,5.46,5.34,4.92,4.48,4.25,4.06,4.08,4.09,4.36,4.26,0.39,0.22,-0.17
38,2024-03-09,5.51,5.48,5.46,5.34,4.92,4.48,4.25,4.06,4.08,4.09,4.36,4.26,0.39,0.22,-0.17
39,2024-03-08,5.51,5.48,5.46,5.34,4.92,4.48,4.25,4.06,4.08,4.09,4.36,4.26,0.39,0.22,-0.17
40,2024-03-07,5.51,5.48,5.47,5.34,4.93,4.50,4.28,4.07,4.09,4.09,4.35,4.25,0.41,0.25,-0.16
41,2024-03-06,5.50,5.47,5.47,5.35,4.95,4.55,4.32,4.12,4.12,4.11,4.36,4.24,0.44,0.31,-0.13
42,2024-03-05,5.50,5.47,5.47,5.35,4.94,4.54,4.32,4.13,4.15,4.13,4.39,4.27,0.41,0.27,-0.14
43,2024-03-04,5.51,5.49,5.48,5.37,4.98,4.61,4.39,4.21,4.23,4.22,4.48,4.36,0.39,0.25,-0.14
44,2024-03-03,5.54,5.49,5.42,5.27,4.94,4.54,4.32,4.17,4.20,4.19,4.46,4.33,0.35,0.21,-0.14
45,2024-03-02,5.54,5.49,5.42,5.27,4.94,4.54,4.32,4.17,4.20,4.19,4.46,4.33,0.35,0.21,-0.14
46,2024-03-01,5.54,5.49,5.42,5.27,4.94,4.54,4.32,4.17,4.20,4.19,4.46,4.33,0.35,0.21,-0.14
47,2024-02-29,5.53,5.50,5.45,5.30,5.01,4.64,4.43,4.26,4.28,4.25,4.51,4.38,0.39,0.26,-0.13
48,2024-02-28,5.50,5.51,5.45,5.31,5.00,4.64,4.44,4.26,4.28,4.27,4.53,4.40,0.37,0.24,-0.13
49,2024-02-27,5.50,5.52,5.45,5.33,5.03,4.70,4.50,4.32,4.34,4.31,4.57,4.44,0.39,0.26,-0.13